worker_processes auto;
events {
    worker_connections 1024;
}

http {
    error_log /dev/stderr debug;
    access_log /dev/stdout;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 600;
    client_body_buffer_size 10M;

    # Tuning buffer settings
    proxy_buffering off;
    proxy_buffer_size 16k;
    proxy_busy_buffers_size 24k;
    proxy_buffers 64 4k;

    # Resolver
    resolver 127.0.0.11 valid=60s; # Docker DNS resolver

    upstream detect {
        server localhost:8000 max_fails=3 fail_timeout=30s;
        keepalive 32;
    }

    upstream feedback {
        server localhost:8001 max_fails=3 fail_timeout=30s;
        keepalive 32;
    }

    server {
        error_log /dev/stderr debug;
        access_log /dev/stdout;
        listen 80;
        server_name cadaid-api.westeurope.azurecontainer.io;

        # Security headers
        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location /detect/ {
            proxy_pass http://detect;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_connect_timeout 60s;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Health check
            health_check interval=5s fails=3 passes=2;
        }

        location /feedback/ {
            
            proxy_pass http://feedback;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_connect_timeout 60s;
            proxy_http_version 1.1;
            proxy_set_header Connection "";

            # Health check
            health_check interval=5s fails=3 passes=2;
        }

        # Redirect root to /detect/docs
        location = / {
            return 301 /detect/docs/;
        }
    }
}
