services:
  detect:
    build:
      context: .
      dockerfile: detect/Dockerfile
    image: cadaidregistry.azurecr.io/detect:latest
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
      - ./shared/static/uploads:/app/static/uploads
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/app:/app/shared
      - STATIC_API_KEY=${STATIC_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - cadaid_network
  feedback:
    build:
      context: .
      dockerfile: feedback/Dockerfile
    image: cadaidregistry.azurecr.io/feedback:latest
    ports:
      - "8001:8001"
    volumes:
      - ./shared:/app/shared
      - ./shared/static/uploads:/app/static/uploads
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/app:/app/shared
      - STATIC_API_KEY=${STATIC_API_KEY}
    networks:
      - cadaid_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: cadaidregistry.azurecr.io/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - detect
      - feedback
    environment:
      - STATIC_API_KEY=${STATIC_API_KEY}
    networks:
      - cadaid_network

networks:
  cadaid_network:
    driver: bridge