FROM python:3.9-slim

# Set environment variables to prevent Python from writing .pyc file
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1




# Set working directory
WORKDIR /app

# Install system dependencies
COPY shared/requirements.txt /app/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
build-essential \
libpoppler-cpp-dev \
pkg-config \
poppler-utils \
wget \
libgl1-mesa-glx \
libglib2.0-0 \
curl \
gnupg \
python3 \
python3-pip \
&& rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

RUN apt-get update && apt-get install -y tesseract-ocr
RUN pip install httpx



# Copy the shared directory before the volume is mounted
COPY shared/ /app/shared

# Create logs directory
RUN mkdir -p /app/logs /app/temp_files /app/static/uploads


# Expose port for the API
EXPOSE 8000 8001

