services:
  detect:
    build:
      context: .
      dockerfile: detect/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./shared:/app/shared
      - ./shared/static/uploads:/app/static/uploads
    environment:
      - PYTHONPATH=/app
      - STATIC_API_KEY=${STATIC_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  feedback:
    build:
      context: .
      dockerfile: feedback/Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./shared:/app/shared
      - ./shared/static/uploads:/app/static/uploads
    environment:
      - PYTHONPATH=/app
      - STATIC_API_KEY=${STATIC_API_KEY}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - detect
      - feedback