services:
  detect:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #image: cadaidregistry.azurecr.io/detect:latest
    #image: detect:latest
    
    volumes:
      - ./detect/src:/app/detect/src # mount detect api code
      - ./shared:/app/shared
      - ./upload_files:/app/upload_files
      - ./shared/.env.dev:/app/.env.dev
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    
    command: uvicorn detect.src.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - cadaid_network
      
  feedback:
    build:
      context: .
      dockerfile: Dockerfile.dev
    #image: cadaidregistry.azurecr.io/feedback:latest
    #image: feedback:latest
    volumes:
      - ./feedback/src:/app/feedback/src # mount feedback api code
      - ./shared:/app/shared
      - ./metadata_files_store:/app/metadata_files_store
      - ./upload_files:/app/upload_files
      - ./shared/.env.dev:/app/.env.dev
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    
    command: uvicorn feedback.src.api:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    networks:
      - cadaid_network
    depends_on:
      - detect

  performance:
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - ./performance/src:/app/performance/src # mount feedback api code
      - ./performance/performance_data:/app/performance_data
      - ./shared:/app/shared
      - ./shared/.env.dev:/app/.env.dev
      - ./detect/src:/app/detect/src
    
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    
    command: uvicorn performance.src.api:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    networks:
      - cadaid_network
    depends_on:
      - detect

  gradio-frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    
    volumes:
      - ./gradio-frontend/src:/app

    command: python /app/app.py 
    ports:
      - 0.0.0.0:"7860:7860"
    networks:
      - cadaid_network

networks:
  cadaid_network:
    driver: bridge